#!/usr/bin/env bash

run-tests () {
    while [ "$#" -ne "0" ]; do
	export SPARK_VERSION="$1"
	echo "==> Running tests with Spark ${SPARK_VERSION} ..."
	R --vanilla --slave -e "devtools::test()"
	shift
    done
}

run-tests 2.0.0 1.6.2 1.6.1

