---
title: "Deployments to Amazon"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: false
aliases:
  /articles/deployment-amazon.html
---

<style>
  .thumbnail {
    border: none;
  }
</style>

```{r setup, include=FALSE}
library(htmltools)

thumbnail <- function(title, img, href, caption = TRUE) {
  div(class = "col-sm-6",
      a(class = "thumbnail", title = title, href = href,
        img(src = img),
        div(class = ifelse(caption, "caption", ""),
          ifelse(caption, title, ""), align="center")))}
```

### Amazon EMR

```{r, echo=FALSE}
div(class = "col-sm-6","This document describes how to setup an EMR cluster, create Hive tables, connect to Spark, analyze data, cache data, train a model, visualize predictions and build a dashboard.")
thumbnail("Amazon EMR", "images/deployment/amazon-emr/emrConfigStep4.png", "deployment-amazon-emr.html")
```


### Amazon EC2

```{r, echo=FALSE}
div(class = "col-sm-6","This document describes how to setup an EC2 cluster using Spark Standalone, configure EC2 instances, configure Spark and RStudio Server.")
thumbnail("Amazon EC2", "images/deployment/amazon-ec2/spark-sa-setup.png", "deployment-amazon-ec2.html")
```

### Amazon S3

```{r, echo=FALSE}
div(class = "col-sm-6","This document describes how to setup pair a Standalone Spark cluster with S3. Unlike in a Hadoop cluster, the data and the computation remain separated thus allowing us repurpose or even tear down the cluster when done. This document covers the packages and settings needed to connect R to Spark in Standalone mode and S3; and a recommended approach to work with data from S3.")
thumbnail("Amazon S3", "images/deployment/amazon-s3/s3-bucket.png", "deployment-amazon-s3.html")
```


