# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: paused

name: Test-Coverage

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      CODE_COVERAGE: 'true'
      ARROW_VERSION: 'release'

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
              any::devtools
              any::sparklyr
              any::qs
              any::e1071
              any::mlbench
              any::glmnet
              any::sparklyr.nested
              any::janeaustenr
              any::reshape2
              any::nycflights13
              any::covr

      - name: Cache Spark
        id: cache-spark
        uses: actions/cache@v3
        with:
          path: /home/runner/spark/spark-3.5.6-bin-hadoop3.2
          key: sparklyr-spark-3.5.6-bin-hadoop3.2

      - name: Install Spark (via sparklyr)
        if: steps.cache-spark.outputs.cache-hit != 'true'
        run: |
          devtools::load_all()
          spark_install(version = "3.5.6")
        shell: Rscript {0}

      - name: Cache Scala
        id: cache-scala
        uses: actions/cache@v3
        with:
          path: /home/runner/scala/
          key: scala-2

      - name: Install Scala (via sparklyr)
        if: steps.cache-scala.outputs.cache-hit != 'true'
        run: |
          devtools::load_all()
          download_scalac()
        shell: Rscript {0}

      - name: Test coverage
        run: |
          identical(Sys.getenv("CODE_COVERAGE"), "true")
          covr::codecov(quiet = FALSE)
        shell: Rscript {0}
